### PR TITLE
Missing keywords

### PR DESCRIPTION
**Pull request by jej**

### CODE REVIEW

**Comment by tinkerspy** [comment]
Thanks!

**Comment by Mike58501** [comment]
Thanks jej ... anything that makes Automaton more user friendly for some of us less skilled is very welcome!

**Comment by jej** [comment]
De nada!
I saw other missing keywords. I think there is a tool to extract them, will investigate...
Thanks for automaton too!

**Comment by jej** [comment]
I found this: https://gist.github.com/don/5748655
Here is the result (on .hpp and .h)

```
#######################################
# Datatypes (KEYWORD1)
#######################################

Appliance KEYWORD1
Automaton KEYWORD1
Factory KEYWORD1
Machine KEYWORD1
Atm_analog KEYWORD1
Atm_bit KEYWORD1
Atm_button KEYWORD1
Atm_command KEYWORD1
Atm_comparator KEYWORD1
Atm_controller KEYWORD1
Atm_digital KEYWORD1
Atm_encoder KEYWORD1
Atm_fade KEYWORD1
Atm_fan KEYWORD1
Atm_led KEYWORD1
Atm_player KEYWORD1
Atm_step KEYWORD1
Atm_timer KEYWORD1
Machine KEYWORD1
atm_connector KEYWORD1
atm_counter KEYWORD1
atm_serial_debug KEYWORD1
atm_timer_millis KEYWORD1

#######################################
# Methods and Functions (KEYWORD2)
#######################################

action KEYWORD2
begin KEYWORD2
cycle KEYWORD2
decrement KEYWORD2
event KEYWORD2
expired KEYWORD2
mapSymbol KEYWORD2
onPush KEYWORD2
print KEYWORD2
println KEYWORD2
push KEYWORD2
set KEYWORD2
setTrace KEYWORD2
sleep KEYWORD2
state KEYWORD2
trace KEYWORD2
trigger KEYWORD2
add KEYWORD2
component KEYWORD2
cycle KEYWORD2
delay KEYWORD2
run KEYWORD2
```

**Comment by jej** [comment]
Found this better tool: https://github.com/r89m/arduino-keywords

Here is the extract it produced:

```
Atm_controller	KEYWORD1
AND	KEYWORD2
IF	KEYWORD2
OR	KEYWORD2
XOR	KEYWORD2
begin	KEYWORD2
led	KEYWORD2
onChange	KEYWORD2
onInput	KEYWORD2
trace	KEYWORD2
Atm_player	KEYWORD1
begin	KEYWORD2
onFinish	KEYWORD2
onNote	KEYWORD2
pitch	KEYWORD2
play	KEYWORD2
repeat	KEYWORD2
speed	KEYWORD2
start	KEYWORD2
state	KEYWORD2
stop	KEYWORD2
toggle	KEYWORD2
trace	KEYWORD2
trigger	KEYWORD2
atm_counter	KEYWORD1
decrement	KEYWORD2
expired	KEYWORD2
set	KEYWORD2
Atm_bit	KEYWORD1
begin	KEYWORD2
input	KEYWORD2
led	KEYWORD2
off	KEYWORD2
on	KEYWORD2
onChange	KEYWORD2
onInput	KEYWORD2
refresh	KEYWORD2
toggle	KEYWORD2
trace	KEYWORD2
atm_connector::union ::	KEYWORD1
atm_connector	KEYWORD1
logOp	KEYWORD2
mode	KEYWORD2
pull	KEYWORD2
push	KEYWORD2
relOp	KEYWORD2
set	KEYWORD2
atm_connector::union 	KEYWORD1
atm_connector::union ::::union 	KEYWORD1
atm_serial_debug	KEYWORD1
trace	KEYWORD2
Atm_encoder	KEYWORD1
begin	KEYWORD2
onChange	KEYWORD2
range	KEYWORD2
set	KEYWORD2
state	KEYWORD2
trace	KEYWORD2
Atm_timer	KEYWORD1
begin	KEYWORD2
interval	KEYWORD2
interval_millis	KEYWORD2
interval_seconds	KEYWORD2
left	KEYWORD2
onFinish	KEYWORD2
onTimer	KEYWORD2
repeat	KEYWORD2
start	KEYWORD2
stop	KEYWORD2
toggle	KEYWORD2
trace	KEYWORD2
Atm_fade	KEYWORD1
begin	KEYWORD2
blink	KEYWORD2
fade	KEYWORD2
off	KEYWORD2
on	KEYWORD2
onFinish	KEYWORD2
pause	KEYWORD2
repeat	KEYWORD2
start	KEYWORD2
toggle	KEYWORD2
toggleBlink	KEYWORD2
trace	KEYWORD2
atm_timer_millis	KEYWORD1
expired	KEYWORD2
set	KEYWORD2
Atm_analog	KEYWORD1
average	KEYWORD2
begin	KEYWORD2
onChange	KEYWORD2
range	KEYWORD2
set	KEYWORD2
state	KEYWORD2
trace	KEYWORD2
Atm_comparator	KEYWORD1
average	KEYWORD2
begin	KEYWORD2
onChange	KEYWORD2
read_sample	KEYWORD2
skip	KEYWORD2
state	KEYWORD2
threshold	KEYWORD2
trace	KEYWORD2
Automaton	KEYWORD1
add	KEYWORD2
delay	KEYWORD2
run	KEYWORD2
Appliance	KEYWORD1
component	KEYWORD2
run	KEYWORD2
Factory	KEYWORD1
add	KEYWORD2
cycle	KEYWORD2
Atm_fan	KEYWORD1
begin	KEYWORD2
onInput	KEYWORD2
state	KEYWORD2
trace	KEYWORD2
trigger	KEYWORD2
Atm_button	KEYWORD1
autoPress	KEYWORD2
begin	KEYWORD2
debounce	KEYWORD2
longPress	KEYWORD2
onPress	KEYWORD2
onRelease	KEYWORD2
repeat	KEYWORD2
trace	KEYWORD2
Atm_command	KEYWORD1
arg	KEYWORD2
begin	KEYWORD2
list	KEYWORD2
lookup	KEYWORD2
onCommand	KEYWORD2
separator	KEYWORD2
trace	KEYWORD2
Atm_digital	KEYWORD1
begin	KEYWORD2
led	KEYWORD2
onChange	KEYWORD2
state	KEYWORD2
trace	KEYWORD2
Machine	KEYWORD1
action	KEYWORD2
cycle	KEYWORD2
event	KEYWORD2
sleep	KEYWORD2
state	KEYWORD2
trigger	KEYWORD2
Atm_step	KEYWORD1
begin	KEYWORD2
onStep	KEYWORD2
state	KEYWORD2
trace	KEYWORD2
Atm_led	KEYWORD1
begin	KEYWORD2
blink	KEYWORD2
brighten	KEYWORD2
brightness	KEYWORD2
fade	KEYWORD2
lead	KEYWORD2
levels	KEYWORD2
off	KEYWORD2
on	KEYWORD2
onFinish	KEYWORD2
pause	KEYWORD2
range	KEYWORD2
repeat	KEYWORD2
start	KEYWORD2
toggle	KEYWORD2
toggleBlink	KEYWORD2
trace	KEYWORD2
trigger	KEYWORD2

```

**Comment by tinkerspy** [comment]
Thanks jej, processed it...

Rgdz,
Tinkerspy

**Comment by jej** [comment]
Thanks too!
I didn't check the output of the script. I hope you did a quick visual check...
J.

**Comment by tinkerspy** [comment]
It looked alright to me...

Rgdz,
Tinkerspy

**Pull request merged**
